version: '3.1'
services:
  app:
    container_name: energy-utility-backend
    image: energy-utility-backend
      - order-pgsql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
      
  dbpostgresql:
    image: dbpostgresql
    container_name: dbpostgresql
    networks:
      - order-pgsql
    ports:
      - "5432:5432"
    volumes: 
      - postgres:/data/postgres

networks:
  order-pgsql:
