version: '3.1'
services:
  backend:
    container_name: energy-utility-backend-container
    image: containerregistryborifazakas30411.azurecr.io/energy-utility-backend-image:latest
    domainname: "energy-utility-backend-bori00"
    networks:
      - order-pgsql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db-container
      
  db-container:
    image: containerregistryborifazakas30411.azurecr.io/db:latest
    container_name: db-container
    networks:
      - order-pgsql
    ports:
      - "5432:5432"
    user: root
    environment:
      - POSTGRES_DB=energy-utility-db
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
    volumes:
      - volpostgres:/var/lib/postgresql/data

volumes:
  - name: volpostgres
    azureFile:
      sharename: acishare
      storageAccountName: bori27866
      storageAccountKey: jaFaWHPP0pO6tFCtCb2K5ddgu0PiUL+qW4gXpqfwey+Xy6daeN0vrUt/I9zPkHmSrbwkTvTo+YxM+ASt2tz71A==

networks:
  order-pgsql:
