version: '3.1'
services:
  energy-utility-backend-container:
    container_name: energy-utility-backend-container
    image: energyutilitybackend
    networks:
      - order-pgsql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db-container
      
  db-container:
    image: postgres:11
    container_name: db-container
    networks:
      - order-pgsql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=energy-utility-db
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password

networks:
  order-pgsql:
