spring:
  application:
    name: Spring Boot On SSL Inside Docker Container
# Server Configuration
server:
  port: 8443
  ssl:
    key-store: classpath:keytool_cert_localhost_ip.p12 # path inside docker container
    key-store-type: PKCS12 # keystore type
    key-alias: mykey # keystore alias
    key-store-password: changeit  # keystore password

debug: false