// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_impl;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ro_tuc_chat_proto_impl_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ro_tuc_chat_proto_impl_ChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ro_tuc_chat_proto_impl_OpenSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ro_tuc_chat_proto_impl_OpenSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ro_tuc_chat_proto_impl_OpenSessionRequestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ro_tuc_chat_proto_impl_OpenSessionRequestResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ro_tuc_chat_proto_impl_MessageReadingStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ro_tuc_chat_proto_impl_MessageReadingStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ro_tuc_chat_proto_impl_MessageTypingStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ro_tuc_chat_proto_impl_MessageTypingStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ro_tuc_chat_proto_impl_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ro_tuc_chat_proto_impl_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ro_tuc_chat_proto_impl_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ro_tuc_chat_proto_impl_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\026ro.tuc.chat.proto_impl\"[\n\013" +
      "ChatMessage\022\024\n\014fromUserName\030\001 \001(\t\022\022\n\ntoU" +
      "serName\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\022\021\n\ttimeSt" +
      "amp\030\004 \001(\t\"*\n\022OpenSessionRequest\022\024\n\014fromU" +
      "serName\030\001 \001(\t\"D\n\032OpenSessionRequestRespo" +
      "nse\022\024\n\014fromUserName\030\001 \001(\t\022\020\n\010accepted\030\002 " +
      "\001(\010\"G\n\024MessageReadingStatus\022\024\n\014fromUserN" +
      "ame\030\001 \001(\t\022\031\n\021readMessagesUntil\030\002 \001(\t\";\n\023" +
      "MessageTypingStatus\022\024\n\014fromUserName\030\001 \001(" +
      "\t\022\016\n\006typing\030\002 \001(\010\"2\n\006Status\022\022\n\nsuccessfu" +
      "l\030\001 \001(\010\022\024\n\014errorMessage\030\002 \001(\t\"\007\n\005Empty2\350" +
      "\006\n\013ChatService\022T\n\013sendMessage\022#.ro.tuc.c" +
      "hat.proto_impl.ChatMessage\032\036.ro.tuc.chat" +
      ".proto_impl.Status\"\000\022X\n\016receiveMessage\022\035" +
      ".ro.tuc.chat.proto_impl.Empty\032#.ro.tuc.c" +
      "hat.proto_impl.ChatMessage\"\0000\001\022j\n\031receiv" +
      "eOpenSessionRequest\022\035.ro.tuc.chat.proto_" +
      "impl.Empty\032*.ro.tuc.chat.proto_impl.Open" +
      "SessionRequest\"\0000\001\022p\n\030acceptOpenSessionR" +
      "equest\0222.ro.tuc.chat.proto_impl.OpenSess" +
      "ionRequestResponse\032\036.ro.tuc.chat.proto_i" +
      "mpl.Status\"\000\022p\n\036sendMessageReadingStatus" +
      "Update\022,.ro.tuc.chat.proto_impl.MessageR" +
      "eadingStatus\032\036.ro.tuc.chat.proto_impl.St" +
      "atus\"\000\022u\n\"receiveMessageReadingStatusUpd" +
      "ates\022\035.ro.tuc.chat.proto_impl.Empty\032,.ro" +
      ".tuc.chat.proto_impl.MessageReadingStatu" +
      "s\"\0000\001\022n\n\035sendMessageTypingStatusUpdate\022+" +
      ".ro.tuc.chat.proto_impl.MessageTypingSta" +
      "tus\032\036.ro.tuc.chat.proto_impl.Status\"\000\022r\n" +
      " receiveMessageTypingStatusUpdate\022\035.ro.t" +
      "uc.chat.proto_impl.Empty\032+.ro.tuc.chat.p" +
      "roto_impl.MessageTypingStatus\"\0000\001B\002P\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ro_tuc_chat_proto_impl_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ro_tuc_chat_proto_impl_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ro_tuc_chat_proto_impl_ChatMessage_descriptor,
        new java.lang.String[] { "FromUserName", "ToUserName", "Message", "TimeStamp", });
    internal_static_ro_tuc_chat_proto_impl_OpenSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ro_tuc_chat_proto_impl_OpenSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ro_tuc_chat_proto_impl_OpenSessionRequest_descriptor,
        new java.lang.String[] { "FromUserName", });
    internal_static_ro_tuc_chat_proto_impl_OpenSessionRequestResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ro_tuc_chat_proto_impl_OpenSessionRequestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ro_tuc_chat_proto_impl_OpenSessionRequestResponse_descriptor,
        new java.lang.String[] { "FromUserName", "Accepted", });
    internal_static_ro_tuc_chat_proto_impl_MessageReadingStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ro_tuc_chat_proto_impl_MessageReadingStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ro_tuc_chat_proto_impl_MessageReadingStatus_descriptor,
        new java.lang.String[] { "FromUserName", "ReadMessagesUntil", });
    internal_static_ro_tuc_chat_proto_impl_MessageTypingStatus_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ro_tuc_chat_proto_impl_MessageTypingStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ro_tuc_chat_proto_impl_MessageTypingStatus_descriptor,
        new java.lang.String[] { "FromUserName", "Typing", });
    internal_static_ro_tuc_chat_proto_impl_Status_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ro_tuc_chat_proto_impl_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ro_tuc_chat_proto_impl_Status_descriptor,
        new java.lang.String[] { "Successful", "ErrorMessage", });
    internal_static_ro_tuc_chat_proto_impl_Empty_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ro_tuc_chat_proto_impl_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ro_tuc_chat_proto_impl_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
