// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_impl;

public interface MessageReadingStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.chat.proto_impl.MessageReadingStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromUserName = 1;</code>
   * @return The fromUserName.
   */
  java.lang.String getFromUserName();
  /**
   * <code>string fromUserName = 1;</code>
   * @return The bytes for fromUserName.
   */
  com.google.protobuf.ByteString
      getFromUserNameBytes();

  /**
   * <code>string readMessagesUntil = 2;</code>
   * @return The readMessagesUntil.
   */
  java.lang.String getReadMessagesUntil();
  /**
   * <code>string readMessagesUntil = 2;</code>
   * @return The bytes for readMessagesUntil.
   */
  com.google.protobuf.ByteString
      getReadMessagesUntilBytes();
}
