// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_impl;

public interface OpenSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.chat.proto_impl.OpenSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromUserName = 1;</code>
   * @return The fromUserName.
   */
  java.lang.String getFromUserName();
  /**
   * <code>string fromUserName = 1;</code>
   * @return The bytes for fromUserName.
   */
  com.google.protobuf.ByteString
      getFromUserNameBytes();
}
