// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

/**
 * Protobuf type {@code ro.tuc.chat.proto_gen.ChatUpdate}
 */
public final class ChatUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ro.tuc.chat.proto_gen.ChatUpdate)
    ChatUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatUpdate.newBuilder() to construct.
  private ChatUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatUpdate() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatUpdate();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_ChatUpdate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_ChatUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ro.tuc.chat.proto_gen.ChatUpdate.class, ro.tuc.chat.proto_gen.ChatUpdate.Builder.class);
  }

  private int updateCase_ = 0;
  private java.lang.Object update_;
  public enum UpdateCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    MESSAGE(1),
    READINGSTATUS(2),
    TYPINGSTATUS(3),
    SESSIONCLOSEDUPDATE(4),
    UPDATE_NOT_SET(0);
    private final int value;
    private UpdateCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UpdateCase valueOf(int value) {
      return forNumber(value);
    }

    public static UpdateCase forNumber(int value) {
      switch (value) {
        case 1: return MESSAGE;
        case 2: return READINGSTATUS;
        case 3: return TYPINGSTATUS;
        case 4: return SESSIONCLOSEDUPDATE;
        case 0: return UPDATE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public UpdateCase
  getUpdateCase() {
    return UpdateCase.forNumber(
        updateCase_);
  }

  public static final int MESSAGE_FIELD_NUMBER = 1;
  /**
   * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return updateCase_ == 1;
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
   * @return The message.
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.ChatMessage getMessage() {
    if (updateCase_ == 1) {
       return (ro.tuc.chat.proto_gen.ChatMessage) update_;
    }
    return ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.ChatMessageOrBuilder getMessageOrBuilder() {
    if (updateCase_ == 1) {
       return (ro.tuc.chat.proto_gen.ChatMessage) update_;
    }
    return ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
  }

  public static final int READINGSTATUS_FIELD_NUMBER = 2;
  /**
   * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
   * @return Whether the readingStatus field is set.
   */
  @java.lang.Override
  public boolean hasReadingStatus() {
    return updateCase_ == 2;
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
   * @return The readingStatus.
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.MessageReadingStatus getReadingStatus() {
    if (updateCase_ == 2) {
       return (ro.tuc.chat.proto_gen.MessageReadingStatus) update_;
    }
    return ro.tuc.chat.proto_gen.MessageReadingStatus.getDefaultInstance();
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.MessageReadingStatusOrBuilder getReadingStatusOrBuilder() {
    if (updateCase_ == 2) {
       return (ro.tuc.chat.proto_gen.MessageReadingStatus) update_;
    }
    return ro.tuc.chat.proto_gen.MessageReadingStatus.getDefaultInstance();
  }

  public static final int TYPINGSTATUS_FIELD_NUMBER = 3;
  /**
   * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
   * @return Whether the typingStatus field is set.
   */
  @java.lang.Override
  public boolean hasTypingStatus() {
    return updateCase_ == 3;
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
   * @return The typingStatus.
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.MessageTypingStatus getTypingStatus() {
    if (updateCase_ == 3) {
       return (ro.tuc.chat.proto_gen.MessageTypingStatus) update_;
    }
    return ro.tuc.chat.proto_gen.MessageTypingStatus.getDefaultInstance();
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.MessageTypingStatusOrBuilder getTypingStatusOrBuilder() {
    if (updateCase_ == 3) {
       return (ro.tuc.chat.proto_gen.MessageTypingStatus) update_;
    }
    return ro.tuc.chat.proto_gen.MessageTypingStatus.getDefaultInstance();
  }

  public static final int SESSIONCLOSEDUPDATE_FIELD_NUMBER = 4;
  /**
   * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
   * @return Whether the sessionClosedUpdate field is set.
   */
  @java.lang.Override
  public boolean hasSessionClosedUpdate() {
    return updateCase_ == 4;
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
   * @return The sessionClosedUpdate.
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.SessionClosedUpdate getSessionClosedUpdate() {
    if (updateCase_ == 4) {
       return (ro.tuc.chat.proto_gen.SessionClosedUpdate) update_;
    }
    return ro.tuc.chat.proto_gen.SessionClosedUpdate.getDefaultInstance();
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.SessionClosedUpdateOrBuilder getSessionClosedUpdateOrBuilder() {
    if (updateCase_ == 4) {
       return (ro.tuc.chat.proto_gen.SessionClosedUpdate) update_;
    }
    return ro.tuc.chat.proto_gen.SessionClosedUpdate.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (updateCase_ == 1) {
      output.writeMessage(1, (ro.tuc.chat.proto_gen.ChatMessage) update_);
    }
    if (updateCase_ == 2) {
      output.writeMessage(2, (ro.tuc.chat.proto_gen.MessageReadingStatus) update_);
    }
    if (updateCase_ == 3) {
      output.writeMessage(3, (ro.tuc.chat.proto_gen.MessageTypingStatus) update_);
    }
    if (updateCase_ == 4) {
      output.writeMessage(4, (ro.tuc.chat.proto_gen.SessionClosedUpdate) update_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (updateCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ro.tuc.chat.proto_gen.ChatMessage) update_);
    }
    if (updateCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ro.tuc.chat.proto_gen.MessageReadingStatus) update_);
    }
    if (updateCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ro.tuc.chat.proto_gen.MessageTypingStatus) update_);
    }
    if (updateCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ro.tuc.chat.proto_gen.SessionClosedUpdate) update_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ro.tuc.chat.proto_gen.ChatUpdate)) {
      return super.equals(obj);
    }
    ro.tuc.chat.proto_gen.ChatUpdate other = (ro.tuc.chat.proto_gen.ChatUpdate) obj;

    if (!getUpdateCase().equals(other.getUpdateCase())) return false;
    switch (updateCase_) {
      case 1:
        if (!getMessage()
            .equals(other.getMessage())) return false;
        break;
      case 2:
        if (!getReadingStatus()
            .equals(other.getReadingStatus())) return false;
        break;
      case 3:
        if (!getTypingStatus()
            .equals(other.getTypingStatus())) return false;
        break;
      case 4:
        if (!getSessionClosedUpdate()
            .equals(other.getSessionClosedUpdate())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (updateCase_) {
      case 1:
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        break;
      case 2:
        hash = (37 * hash) + READINGSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getReadingStatus().hashCode();
        break;
      case 3:
        hash = (37 * hash) + TYPINGSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getTypingStatus().hashCode();
        break;
      case 4:
        hash = (37 * hash) + SESSIONCLOSEDUPDATE_FIELD_NUMBER;
        hash = (53 * hash) + getSessionClosedUpdate().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ro.tuc.chat.proto_gen.ChatUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.ChatUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ro.tuc.chat.proto_gen.ChatUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ro.tuc.chat.proto_gen.ChatUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ro.tuc.chat.proto_gen.ChatUpdate)
      ro.tuc.chat.proto_gen.ChatUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_ChatUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_ChatUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ro.tuc.chat.proto_gen.ChatUpdate.class, ro.tuc.chat.proto_gen.ChatUpdate.Builder.class);
    }

    // Construct using ro.tuc.chat.proto_gen.ChatUpdate.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (messageBuilder_ != null) {
        messageBuilder_.clear();
      }
      if (readingStatusBuilder_ != null) {
        readingStatusBuilder_.clear();
      }
      if (typingStatusBuilder_ != null) {
        typingStatusBuilder_.clear();
      }
      if (sessionClosedUpdateBuilder_ != null) {
        sessionClosedUpdateBuilder_.clear();
      }
      updateCase_ = 0;
      update_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_ChatUpdate_descriptor;
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.ChatUpdate getDefaultInstanceForType() {
      return ro.tuc.chat.proto_gen.ChatUpdate.getDefaultInstance();
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.ChatUpdate build() {
      ro.tuc.chat.proto_gen.ChatUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.ChatUpdate buildPartial() {
      ro.tuc.chat.proto_gen.ChatUpdate result = new ro.tuc.chat.proto_gen.ChatUpdate(this);
      if (updateCase_ == 1) {
        if (messageBuilder_ == null) {
          result.update_ = update_;
        } else {
          result.update_ = messageBuilder_.build();
        }
      }
      if (updateCase_ == 2) {
        if (readingStatusBuilder_ == null) {
          result.update_ = update_;
        } else {
          result.update_ = readingStatusBuilder_.build();
        }
      }
      if (updateCase_ == 3) {
        if (typingStatusBuilder_ == null) {
          result.update_ = update_;
        } else {
          result.update_ = typingStatusBuilder_.build();
        }
      }
      if (updateCase_ == 4) {
        if (sessionClosedUpdateBuilder_ == null) {
          result.update_ = update_;
        } else {
          result.update_ = sessionClosedUpdateBuilder_.build();
        }
      }
      result.updateCase_ = updateCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ro.tuc.chat.proto_gen.ChatUpdate) {
        return mergeFrom((ro.tuc.chat.proto_gen.ChatUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ro.tuc.chat.proto_gen.ChatUpdate other) {
      if (other == ro.tuc.chat.proto_gen.ChatUpdate.getDefaultInstance()) return this;
      switch (other.getUpdateCase()) {
        case MESSAGE: {
          mergeMessage(other.getMessage());
          break;
        }
        case READINGSTATUS: {
          mergeReadingStatus(other.getReadingStatus());
          break;
        }
        case TYPINGSTATUS: {
          mergeTypingStatus(other.getTypingStatus());
          break;
        }
        case SESSIONCLOSEDUPDATE: {
          mergeSessionClosedUpdate(other.getSessionClosedUpdate());
          break;
        }
        case UPDATE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              updateCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getReadingStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              updateCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getTypingStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              updateCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getSessionClosedUpdateFieldBuilder().getBuilder(),
                  extensionRegistry);
              updateCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int updateCase_ = 0;
    private java.lang.Object update_;
    public UpdateCase
        getUpdateCase() {
      return UpdateCase.forNumber(
          updateCase_);
    }

    public Builder clearUpdate() {
      updateCase_ = 0;
      update_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.ChatMessage, ro.tuc.chat.proto_gen.ChatMessage.Builder, ro.tuc.chat.proto_gen.ChatMessageOrBuilder> messageBuilder_;
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return updateCase_ == 1;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.ChatMessage getMessage() {
      if (messageBuilder_ == null) {
        if (updateCase_ == 1) {
          return (ro.tuc.chat.proto_gen.ChatMessage) update_;
        }
        return ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
      } else {
        if (updateCase_ == 1) {
          return messageBuilder_.getMessage();
        }
        return ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
     */
    public Builder setMessage(ro.tuc.chat.proto_gen.ChatMessage value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        update_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }
      updateCase_ = 1;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
     */
    public Builder setMessage(
        ro.tuc.chat.proto_gen.ChatMessage.Builder builderForValue) {
      if (messageBuilder_ == null) {
        update_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      updateCase_ = 1;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
     */
    public Builder mergeMessage(ro.tuc.chat.proto_gen.ChatMessage value) {
      if (messageBuilder_ == null) {
        if (updateCase_ == 1 &&
            update_ != ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance()) {
          update_ = ro.tuc.chat.proto_gen.ChatMessage.newBuilder((ro.tuc.chat.proto_gen.ChatMessage) update_)
              .mergeFrom(value).buildPartial();
        } else {
          update_ = value;
        }
        onChanged();
      } else {
        if (updateCase_ == 1) {
          messageBuilder_.mergeFrom(value);
        } else {
          messageBuilder_.setMessage(value);
        }
      }
      updateCase_ = 1;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        if (updateCase_ == 1) {
          updateCase_ = 0;
          update_ = null;
          onChanged();
        }
      } else {
        if (updateCase_ == 1) {
          updateCase_ = 0;
          update_ = null;
        }
        messageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
     */
    public ro.tuc.chat.proto_gen.ChatMessage.Builder getMessageBuilder() {
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.ChatMessageOrBuilder getMessageOrBuilder() {
      if ((updateCase_ == 1) && (messageBuilder_ != null)) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        if (updateCase_ == 1) {
          return (ro.tuc.chat.proto_gen.ChatMessage) update_;
        }
        return ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage message = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.ChatMessage, ro.tuc.chat.proto_gen.ChatMessage.Builder, ro.tuc.chat.proto_gen.ChatMessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        if (!(updateCase_ == 1)) {
          update_ = ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
        }
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ro.tuc.chat.proto_gen.ChatMessage, ro.tuc.chat.proto_gen.ChatMessage.Builder, ro.tuc.chat.proto_gen.ChatMessageOrBuilder>(
                (ro.tuc.chat.proto_gen.ChatMessage) update_,
                getParentForChildren(),
                isClean());
        update_ = null;
      }
      updateCase_ = 1;
      onChanged();;
      return messageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.MessageReadingStatus, ro.tuc.chat.proto_gen.MessageReadingStatus.Builder, ro.tuc.chat.proto_gen.MessageReadingStatusOrBuilder> readingStatusBuilder_;
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
     * @return Whether the readingStatus field is set.
     */
    @java.lang.Override
    public boolean hasReadingStatus() {
      return updateCase_ == 2;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
     * @return The readingStatus.
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.MessageReadingStatus getReadingStatus() {
      if (readingStatusBuilder_ == null) {
        if (updateCase_ == 2) {
          return (ro.tuc.chat.proto_gen.MessageReadingStatus) update_;
        }
        return ro.tuc.chat.proto_gen.MessageReadingStatus.getDefaultInstance();
      } else {
        if (updateCase_ == 2) {
          return readingStatusBuilder_.getMessage();
        }
        return ro.tuc.chat.proto_gen.MessageReadingStatus.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
     */
    public Builder setReadingStatus(ro.tuc.chat.proto_gen.MessageReadingStatus value) {
      if (readingStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        update_ = value;
        onChanged();
      } else {
        readingStatusBuilder_.setMessage(value);
      }
      updateCase_ = 2;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
     */
    public Builder setReadingStatus(
        ro.tuc.chat.proto_gen.MessageReadingStatus.Builder builderForValue) {
      if (readingStatusBuilder_ == null) {
        update_ = builderForValue.build();
        onChanged();
      } else {
        readingStatusBuilder_.setMessage(builderForValue.build());
      }
      updateCase_ = 2;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
     */
    public Builder mergeReadingStatus(ro.tuc.chat.proto_gen.MessageReadingStatus value) {
      if (readingStatusBuilder_ == null) {
        if (updateCase_ == 2 &&
            update_ != ro.tuc.chat.proto_gen.MessageReadingStatus.getDefaultInstance()) {
          update_ = ro.tuc.chat.proto_gen.MessageReadingStatus.newBuilder((ro.tuc.chat.proto_gen.MessageReadingStatus) update_)
              .mergeFrom(value).buildPartial();
        } else {
          update_ = value;
        }
        onChanged();
      } else {
        if (updateCase_ == 2) {
          readingStatusBuilder_.mergeFrom(value);
        } else {
          readingStatusBuilder_.setMessage(value);
        }
      }
      updateCase_ = 2;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
     */
    public Builder clearReadingStatus() {
      if (readingStatusBuilder_ == null) {
        if (updateCase_ == 2) {
          updateCase_ = 0;
          update_ = null;
          onChanged();
        }
      } else {
        if (updateCase_ == 2) {
          updateCase_ = 0;
          update_ = null;
        }
        readingStatusBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
     */
    public ro.tuc.chat.proto_gen.MessageReadingStatus.Builder getReadingStatusBuilder() {
      return getReadingStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.MessageReadingStatusOrBuilder getReadingStatusOrBuilder() {
      if ((updateCase_ == 2) && (readingStatusBuilder_ != null)) {
        return readingStatusBuilder_.getMessageOrBuilder();
      } else {
        if (updateCase_ == 2) {
          return (ro.tuc.chat.proto_gen.MessageReadingStatus) update_;
        }
        return ro.tuc.chat.proto_gen.MessageReadingStatus.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageReadingStatus readingStatus = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.MessageReadingStatus, ro.tuc.chat.proto_gen.MessageReadingStatus.Builder, ro.tuc.chat.proto_gen.MessageReadingStatusOrBuilder> 
        getReadingStatusFieldBuilder() {
      if (readingStatusBuilder_ == null) {
        if (!(updateCase_ == 2)) {
          update_ = ro.tuc.chat.proto_gen.MessageReadingStatus.getDefaultInstance();
        }
        readingStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ro.tuc.chat.proto_gen.MessageReadingStatus, ro.tuc.chat.proto_gen.MessageReadingStatus.Builder, ro.tuc.chat.proto_gen.MessageReadingStatusOrBuilder>(
                (ro.tuc.chat.proto_gen.MessageReadingStatus) update_,
                getParentForChildren(),
                isClean());
        update_ = null;
      }
      updateCase_ = 2;
      onChanged();;
      return readingStatusBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.MessageTypingStatus, ro.tuc.chat.proto_gen.MessageTypingStatus.Builder, ro.tuc.chat.proto_gen.MessageTypingStatusOrBuilder> typingStatusBuilder_;
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
     * @return Whether the typingStatus field is set.
     */
    @java.lang.Override
    public boolean hasTypingStatus() {
      return updateCase_ == 3;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
     * @return The typingStatus.
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.MessageTypingStatus getTypingStatus() {
      if (typingStatusBuilder_ == null) {
        if (updateCase_ == 3) {
          return (ro.tuc.chat.proto_gen.MessageTypingStatus) update_;
        }
        return ro.tuc.chat.proto_gen.MessageTypingStatus.getDefaultInstance();
      } else {
        if (updateCase_ == 3) {
          return typingStatusBuilder_.getMessage();
        }
        return ro.tuc.chat.proto_gen.MessageTypingStatus.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
     */
    public Builder setTypingStatus(ro.tuc.chat.proto_gen.MessageTypingStatus value) {
      if (typingStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        update_ = value;
        onChanged();
      } else {
        typingStatusBuilder_.setMessage(value);
      }
      updateCase_ = 3;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
     */
    public Builder setTypingStatus(
        ro.tuc.chat.proto_gen.MessageTypingStatus.Builder builderForValue) {
      if (typingStatusBuilder_ == null) {
        update_ = builderForValue.build();
        onChanged();
      } else {
        typingStatusBuilder_.setMessage(builderForValue.build());
      }
      updateCase_ = 3;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
     */
    public Builder mergeTypingStatus(ro.tuc.chat.proto_gen.MessageTypingStatus value) {
      if (typingStatusBuilder_ == null) {
        if (updateCase_ == 3 &&
            update_ != ro.tuc.chat.proto_gen.MessageTypingStatus.getDefaultInstance()) {
          update_ = ro.tuc.chat.proto_gen.MessageTypingStatus.newBuilder((ro.tuc.chat.proto_gen.MessageTypingStatus) update_)
              .mergeFrom(value).buildPartial();
        } else {
          update_ = value;
        }
        onChanged();
      } else {
        if (updateCase_ == 3) {
          typingStatusBuilder_.mergeFrom(value);
        } else {
          typingStatusBuilder_.setMessage(value);
        }
      }
      updateCase_ = 3;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
     */
    public Builder clearTypingStatus() {
      if (typingStatusBuilder_ == null) {
        if (updateCase_ == 3) {
          updateCase_ = 0;
          update_ = null;
          onChanged();
        }
      } else {
        if (updateCase_ == 3) {
          updateCase_ = 0;
          update_ = null;
        }
        typingStatusBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
     */
    public ro.tuc.chat.proto_gen.MessageTypingStatus.Builder getTypingStatusBuilder() {
      return getTypingStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.MessageTypingStatusOrBuilder getTypingStatusOrBuilder() {
      if ((updateCase_ == 3) && (typingStatusBuilder_ != null)) {
        return typingStatusBuilder_.getMessageOrBuilder();
      } else {
        if (updateCase_ == 3) {
          return (ro.tuc.chat.proto_gen.MessageTypingStatus) update_;
        }
        return ro.tuc.chat.proto_gen.MessageTypingStatus.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.MessageTypingStatus typingStatus = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.MessageTypingStatus, ro.tuc.chat.proto_gen.MessageTypingStatus.Builder, ro.tuc.chat.proto_gen.MessageTypingStatusOrBuilder> 
        getTypingStatusFieldBuilder() {
      if (typingStatusBuilder_ == null) {
        if (!(updateCase_ == 3)) {
          update_ = ro.tuc.chat.proto_gen.MessageTypingStatus.getDefaultInstance();
        }
        typingStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ro.tuc.chat.proto_gen.MessageTypingStatus, ro.tuc.chat.proto_gen.MessageTypingStatus.Builder, ro.tuc.chat.proto_gen.MessageTypingStatusOrBuilder>(
                (ro.tuc.chat.proto_gen.MessageTypingStatus) update_,
                getParentForChildren(),
                isClean());
        update_ = null;
      }
      updateCase_ = 3;
      onChanged();;
      return typingStatusBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.SessionClosedUpdate, ro.tuc.chat.proto_gen.SessionClosedUpdate.Builder, ro.tuc.chat.proto_gen.SessionClosedUpdateOrBuilder> sessionClosedUpdateBuilder_;
    /**
     * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
     * @return Whether the sessionClosedUpdate field is set.
     */
    @java.lang.Override
    public boolean hasSessionClosedUpdate() {
      return updateCase_ == 4;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
     * @return The sessionClosedUpdate.
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.SessionClosedUpdate getSessionClosedUpdate() {
      if (sessionClosedUpdateBuilder_ == null) {
        if (updateCase_ == 4) {
          return (ro.tuc.chat.proto_gen.SessionClosedUpdate) update_;
        }
        return ro.tuc.chat.proto_gen.SessionClosedUpdate.getDefaultInstance();
      } else {
        if (updateCase_ == 4) {
          return sessionClosedUpdateBuilder_.getMessage();
        }
        return ro.tuc.chat.proto_gen.SessionClosedUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
     */
    public Builder setSessionClosedUpdate(ro.tuc.chat.proto_gen.SessionClosedUpdate value) {
      if (sessionClosedUpdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        update_ = value;
        onChanged();
      } else {
        sessionClosedUpdateBuilder_.setMessage(value);
      }
      updateCase_ = 4;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
     */
    public Builder setSessionClosedUpdate(
        ro.tuc.chat.proto_gen.SessionClosedUpdate.Builder builderForValue) {
      if (sessionClosedUpdateBuilder_ == null) {
        update_ = builderForValue.build();
        onChanged();
      } else {
        sessionClosedUpdateBuilder_.setMessage(builderForValue.build());
      }
      updateCase_ = 4;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
     */
    public Builder mergeSessionClosedUpdate(ro.tuc.chat.proto_gen.SessionClosedUpdate value) {
      if (sessionClosedUpdateBuilder_ == null) {
        if (updateCase_ == 4 &&
            update_ != ro.tuc.chat.proto_gen.SessionClosedUpdate.getDefaultInstance()) {
          update_ = ro.tuc.chat.proto_gen.SessionClosedUpdate.newBuilder((ro.tuc.chat.proto_gen.SessionClosedUpdate) update_)
              .mergeFrom(value).buildPartial();
        } else {
          update_ = value;
        }
        onChanged();
      } else {
        if (updateCase_ == 4) {
          sessionClosedUpdateBuilder_.mergeFrom(value);
        } else {
          sessionClosedUpdateBuilder_.setMessage(value);
        }
      }
      updateCase_ = 4;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
     */
    public Builder clearSessionClosedUpdate() {
      if (sessionClosedUpdateBuilder_ == null) {
        if (updateCase_ == 4) {
          updateCase_ = 0;
          update_ = null;
          onChanged();
        }
      } else {
        if (updateCase_ == 4) {
          updateCase_ = 0;
          update_ = null;
        }
        sessionClosedUpdateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
     */
    public ro.tuc.chat.proto_gen.SessionClosedUpdate.Builder getSessionClosedUpdateBuilder() {
      return getSessionClosedUpdateFieldBuilder().getBuilder();
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.SessionClosedUpdateOrBuilder getSessionClosedUpdateOrBuilder() {
      if ((updateCase_ == 4) && (sessionClosedUpdateBuilder_ != null)) {
        return sessionClosedUpdateBuilder_.getMessageOrBuilder();
      } else {
        if (updateCase_ == 4) {
          return (ro.tuc.chat.proto_gen.SessionClosedUpdate) update_;
        }
        return ro.tuc.chat.proto_gen.SessionClosedUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.SessionClosedUpdate sessionClosedUpdate = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.SessionClosedUpdate, ro.tuc.chat.proto_gen.SessionClosedUpdate.Builder, ro.tuc.chat.proto_gen.SessionClosedUpdateOrBuilder> 
        getSessionClosedUpdateFieldBuilder() {
      if (sessionClosedUpdateBuilder_ == null) {
        if (!(updateCase_ == 4)) {
          update_ = ro.tuc.chat.proto_gen.SessionClosedUpdate.getDefaultInstance();
        }
        sessionClosedUpdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ro.tuc.chat.proto_gen.SessionClosedUpdate, ro.tuc.chat.proto_gen.SessionClosedUpdate.Builder, ro.tuc.chat.proto_gen.SessionClosedUpdateOrBuilder>(
                (ro.tuc.chat.proto_gen.SessionClosedUpdate) update_,
                getParentForChildren(),
                isClean());
        update_ = null;
      }
      updateCase_ = 4;
      onChanged();;
      return sessionClosedUpdateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ro.tuc.chat.proto_gen.ChatUpdate)
  }

  // @@protoc_insertion_point(class_scope:ro.tuc.chat.proto_gen.ChatUpdate)
  private static final ro.tuc.chat.proto_gen.ChatUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ro.tuc.chat.proto_gen.ChatUpdate();
  }

  public static ro.tuc.chat.proto_gen.ChatUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatUpdate>
      PARSER = new com.google.protobuf.AbstractParser<ChatUpdate>() {
    @java.lang.Override
    public ChatUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatUpdate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ro.tuc.chat.proto_gen.ChatUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

