// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

public interface ChatMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.chat.proto_gen.ChatMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recipientName = 1;</code>
   * @return The recipientName.
   */
  java.lang.String getRecipientName();
  /**
   * <code>string recipientName = 1;</code>
   * @return The bytes for recipientName.
   */
  com.google.protobuf.ByteString
      getRecipientNameBytes();

  /**
   * <code>string senderName = 2;</code>
   * @return The senderName.
   */
  java.lang.String getSenderName();
  /**
   * <code>string senderName = 2;</code>
   * @return The bytes for senderName.
   */
  com.google.protobuf.ByteString
      getSenderNameBytes();
}
