// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.chat.proto_gen.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromUserName = 1;</code>
   * @return The fromUserName.
   */
  java.lang.String getFromUserName();
  /**
   * <code>string fromUserName = 1;</code>
   * @return The bytes for fromUserName.
   */
  com.google.protobuf.ByteString
      getFromUserNameBytes();

  /**
   * <code>string toUserName = 2;</code>
   * @return The toUserName.
   */
  java.lang.String getToUserName();
  /**
   * <code>string toUserName = 2;</code>
   * @return The bytes for toUserName.
   */
  com.google.protobuf.ByteString
      getToUserNameBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string timeStamp = 4;</code>
   * @return The timeStamp.
   */
  java.lang.String getTimeStamp();
  /**
   * <code>string timeStamp = 4;</code>
   * @return The bytes for timeStamp.
   */
  com.google.protobuf.ByteString
      getTimeStampBytes();
}
