// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

/**
 * Protobuf type {@code ro.tuc.chat.proto_gen.ChatMessageRequest}
 */
public final class ChatMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ro.tuc.chat.proto_gen.ChatMessageRequest)
    ChatMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatMessageRequest.newBuilder() to construct.
  private ChatMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatMessageRequest() {
    recipientName_ = "";
    senderName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatMessageRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_ChatMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_ChatMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ro.tuc.chat.proto_gen.ChatMessageRequest.class, ro.tuc.chat.proto_gen.ChatMessageRequest.Builder.class);
  }

  public static final int RECIPIENTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object recipientName_;
  /**
   * <code>string recipientName = 1;</code>
   * @return The recipientName.
   */
  @java.lang.Override
  public java.lang.String getRecipientName() {
    java.lang.Object ref = recipientName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recipientName_ = s;
      return s;
    }
  }
  /**
   * <code>string recipientName = 1;</code>
   * @return The bytes for recipientName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecipientNameBytes() {
    java.lang.Object ref = recipientName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recipientName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object senderName_;
  /**
   * <code>string senderName = 2;</code>
   * @return The senderName.
   */
  @java.lang.Override
  public java.lang.String getSenderName() {
    java.lang.Object ref = senderName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderName_ = s;
      return s;
    }
  }
  /**
   * <code>string senderName = 2;</code>
   * @return The bytes for senderName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderNameBytes() {
    java.lang.Object ref = senderName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recipientName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, recipientName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recipientName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, recipientName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ro.tuc.chat.proto_gen.ChatMessageRequest)) {
      return super.equals(obj);
    }
    ro.tuc.chat.proto_gen.ChatMessageRequest other = (ro.tuc.chat.proto_gen.ChatMessageRequest) obj;

    if (!getRecipientName()
        .equals(other.getRecipientName())) return false;
    if (!getSenderName()
        .equals(other.getSenderName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECIPIENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRecipientName().hashCode();
    hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSenderName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.ChatMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ro.tuc.chat.proto_gen.ChatMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ro.tuc.chat.proto_gen.ChatMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ro.tuc.chat.proto_gen.ChatMessageRequest)
      ro.tuc.chat.proto_gen.ChatMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_ChatMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_ChatMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ro.tuc.chat.proto_gen.ChatMessageRequest.class, ro.tuc.chat.proto_gen.ChatMessageRequest.Builder.class);
    }

    // Construct using ro.tuc.chat.proto_gen.ChatMessageRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      recipientName_ = "";

      senderName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_ChatMessageRequest_descriptor;
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.ChatMessageRequest getDefaultInstanceForType() {
      return ro.tuc.chat.proto_gen.ChatMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.ChatMessageRequest build() {
      ro.tuc.chat.proto_gen.ChatMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.ChatMessageRequest buildPartial() {
      ro.tuc.chat.proto_gen.ChatMessageRequest result = new ro.tuc.chat.proto_gen.ChatMessageRequest(this);
      result.recipientName_ = recipientName_;
      result.senderName_ = senderName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ro.tuc.chat.proto_gen.ChatMessageRequest) {
        return mergeFrom((ro.tuc.chat.proto_gen.ChatMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ro.tuc.chat.proto_gen.ChatMessageRequest other) {
      if (other == ro.tuc.chat.proto_gen.ChatMessageRequest.getDefaultInstance()) return this;
      if (!other.getRecipientName().isEmpty()) {
        recipientName_ = other.recipientName_;
        onChanged();
      }
      if (!other.getSenderName().isEmpty()) {
        senderName_ = other.senderName_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              recipientName_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              senderName_ = input.readStringRequireUtf8();

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object recipientName_ = "";
    /**
     * <code>string recipientName = 1;</code>
     * @return The recipientName.
     */
    public java.lang.String getRecipientName() {
      java.lang.Object ref = recipientName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recipientName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string recipientName = 1;</code>
     * @return The bytes for recipientName.
     */
    public com.google.protobuf.ByteString
        getRecipientNameBytes() {
      java.lang.Object ref = recipientName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recipientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string recipientName = 1;</code>
     * @param value The recipientName to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recipientName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string recipientName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipientName() {
      
      recipientName_ = getDefaultInstance().getRecipientName();
      onChanged();
      return this;
    }
    /**
     * <code>string recipientName = 1;</code>
     * @param value The bytes for recipientName to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recipientName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object senderName_ = "";
    /**
     * <code>string senderName = 2;</code>
     * @return The senderName.
     */
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string senderName = 2;</code>
     * @return The bytes for senderName.
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string senderName = 2;</code>
     * @param value The senderName to set.
     * @return This builder for chaining.
     */
    public Builder setSenderName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string senderName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderName() {
      
      senderName_ = getDefaultInstance().getSenderName();
      onChanged();
      return this;
    }
    /**
     * <code>string senderName = 2;</code>
     * @param value The bytes for senderName to set.
     * @return This builder for chaining.
     */
    public Builder setSenderNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ro.tuc.chat.proto_gen.ChatMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:ro.tuc.chat.proto_gen.ChatMessageRequest)
  private static final ro.tuc.chat.proto_gen.ChatMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ro.tuc.chat.proto_gen.ChatMessageRequest();
  }

  public static ro.tuc.chat.proto_gen.ChatMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<ChatMessageRequest>() {
    @java.lang.Override
    public ChatMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ro.tuc.chat.proto_gen.ChatMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

