// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

/**
 * Protobuf type {@code ro.tuc.chat.proto_gen.MessageReadingStatus}
 */
public final class MessageReadingStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ro.tuc.chat.proto_gen.MessageReadingStatus)
    MessageReadingStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageReadingStatus.newBuilder() to construct.
  private MessageReadingStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageReadingStatus() {
    readerUserName_ = "";
    senderUserName_ = "";
    readMessagesUntil_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageReadingStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_MessageReadingStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_MessageReadingStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ro.tuc.chat.proto_gen.MessageReadingStatus.class, ro.tuc.chat.proto_gen.MessageReadingStatus.Builder.class);
  }

  public static final int READERUSERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object readerUserName_;
  /**
   * <code>string readerUserName = 1;</code>
   * @return The readerUserName.
   */
  @java.lang.Override
  public java.lang.String getReaderUserName() {
    java.lang.Object ref = readerUserName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      readerUserName_ = s;
      return s;
    }
  }
  /**
   * <code>string readerUserName = 1;</code>
   * @return The bytes for readerUserName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReaderUserNameBytes() {
    java.lang.Object ref = readerUserName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      readerUserName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDERUSERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object senderUserName_;
  /**
   * <code>string senderUserName = 2;</code>
   * @return The senderUserName.
   */
  @java.lang.Override
  public java.lang.String getSenderUserName() {
    java.lang.Object ref = senderUserName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderUserName_ = s;
      return s;
    }
  }
  /**
   * <code>string senderUserName = 2;</code>
   * @return The bytes for senderUserName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderUserNameBytes() {
    java.lang.Object ref = senderUserName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderUserName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int READMESSAGESUNTIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object readMessagesUntil_;
  /**
   * <code>string readMessagesUntil = 3;</code>
   * @return The readMessagesUntil.
   */
  @java.lang.Override
  public java.lang.String getReadMessagesUntil() {
    java.lang.Object ref = readMessagesUntil_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      readMessagesUntil_ = s;
      return s;
    }
  }
  /**
   * <code>string readMessagesUntil = 3;</code>
   * @return The bytes for readMessagesUntil.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReadMessagesUntilBytes() {
    java.lang.Object ref = readMessagesUntil_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      readMessagesUntil_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(readerUserName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, readerUserName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderUserName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderUserName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(readMessagesUntil_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, readMessagesUntil_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(readerUserName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, readerUserName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderUserName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderUserName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(readMessagesUntil_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, readMessagesUntil_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ro.tuc.chat.proto_gen.MessageReadingStatus)) {
      return super.equals(obj);
    }
    ro.tuc.chat.proto_gen.MessageReadingStatus other = (ro.tuc.chat.proto_gen.MessageReadingStatus) obj;

    if (!getReaderUserName()
        .equals(other.getReaderUserName())) return false;
    if (!getSenderUserName()
        .equals(other.getSenderUserName())) return false;
    if (!getReadMessagesUntil()
        .equals(other.getReadMessagesUntil())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + READERUSERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getReaderUserName().hashCode();
    hash = (37 * hash) + SENDERUSERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSenderUserName().hashCode();
    hash = (37 * hash) + READMESSAGESUNTIL_FIELD_NUMBER;
    hash = (53 * hash) + getReadMessagesUntil().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.MessageReadingStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ro.tuc.chat.proto_gen.MessageReadingStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ro.tuc.chat.proto_gen.MessageReadingStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ro.tuc.chat.proto_gen.MessageReadingStatus)
      ro.tuc.chat.proto_gen.MessageReadingStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_MessageReadingStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_MessageReadingStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ro.tuc.chat.proto_gen.MessageReadingStatus.class, ro.tuc.chat.proto_gen.MessageReadingStatus.Builder.class);
    }

    // Construct using ro.tuc.chat.proto_gen.MessageReadingStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      readerUserName_ = "";

      senderUserName_ = "";

      readMessagesUntil_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_MessageReadingStatus_descriptor;
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.MessageReadingStatus getDefaultInstanceForType() {
      return ro.tuc.chat.proto_gen.MessageReadingStatus.getDefaultInstance();
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.MessageReadingStatus build() {
      ro.tuc.chat.proto_gen.MessageReadingStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.MessageReadingStatus buildPartial() {
      ro.tuc.chat.proto_gen.MessageReadingStatus result = new ro.tuc.chat.proto_gen.MessageReadingStatus(this);
      result.readerUserName_ = readerUserName_;
      result.senderUserName_ = senderUserName_;
      result.readMessagesUntil_ = readMessagesUntil_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ro.tuc.chat.proto_gen.MessageReadingStatus) {
        return mergeFrom((ro.tuc.chat.proto_gen.MessageReadingStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ro.tuc.chat.proto_gen.MessageReadingStatus other) {
      if (other == ro.tuc.chat.proto_gen.MessageReadingStatus.getDefaultInstance()) return this;
      if (!other.getReaderUserName().isEmpty()) {
        readerUserName_ = other.readerUserName_;
        onChanged();
      }
      if (!other.getSenderUserName().isEmpty()) {
        senderUserName_ = other.senderUserName_;
        onChanged();
      }
      if (!other.getReadMessagesUntil().isEmpty()) {
        readMessagesUntil_ = other.readMessagesUntil_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              readerUserName_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              senderUserName_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              readMessagesUntil_ = input.readStringRequireUtf8();

              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object readerUserName_ = "";
    /**
     * <code>string readerUserName = 1;</code>
     * @return The readerUserName.
     */
    public java.lang.String getReaderUserName() {
      java.lang.Object ref = readerUserName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readerUserName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string readerUserName = 1;</code>
     * @return The bytes for readerUserName.
     */
    public com.google.protobuf.ByteString
        getReaderUserNameBytes() {
      java.lang.Object ref = readerUserName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readerUserName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string readerUserName = 1;</code>
     * @param value The readerUserName to set.
     * @return This builder for chaining.
     */
    public Builder setReaderUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      readerUserName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string readerUserName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReaderUserName() {
      
      readerUserName_ = getDefaultInstance().getReaderUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string readerUserName = 1;</code>
     * @param value The bytes for readerUserName to set.
     * @return This builder for chaining.
     */
    public Builder setReaderUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      readerUserName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object senderUserName_ = "";
    /**
     * <code>string senderUserName = 2;</code>
     * @return The senderUserName.
     */
    public java.lang.String getSenderUserName() {
      java.lang.Object ref = senderUserName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderUserName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string senderUserName = 2;</code>
     * @return The bytes for senderUserName.
     */
    public com.google.protobuf.ByteString
        getSenderUserNameBytes() {
      java.lang.Object ref = senderUserName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderUserName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string senderUserName = 2;</code>
     * @param value The senderUserName to set.
     * @return This builder for chaining.
     */
    public Builder setSenderUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderUserName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string senderUserName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderUserName() {
      
      senderUserName_ = getDefaultInstance().getSenderUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string senderUserName = 2;</code>
     * @param value The bytes for senderUserName to set.
     * @return This builder for chaining.
     */
    public Builder setSenderUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderUserName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object readMessagesUntil_ = "";
    /**
     * <code>string readMessagesUntil = 3;</code>
     * @return The readMessagesUntil.
     */
    public java.lang.String getReadMessagesUntil() {
      java.lang.Object ref = readMessagesUntil_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readMessagesUntil_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string readMessagesUntil = 3;</code>
     * @return The bytes for readMessagesUntil.
     */
    public com.google.protobuf.ByteString
        getReadMessagesUntilBytes() {
      java.lang.Object ref = readMessagesUntil_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readMessagesUntil_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string readMessagesUntil = 3;</code>
     * @param value The readMessagesUntil to set.
     * @return This builder for chaining.
     */
    public Builder setReadMessagesUntil(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      readMessagesUntil_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string readMessagesUntil = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadMessagesUntil() {
      
      readMessagesUntil_ = getDefaultInstance().getReadMessagesUntil();
      onChanged();
      return this;
    }
    /**
     * <code>string readMessagesUntil = 3;</code>
     * @param value The bytes for readMessagesUntil to set.
     * @return This builder for chaining.
     */
    public Builder setReadMessagesUntilBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      readMessagesUntil_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ro.tuc.chat.proto_gen.MessageReadingStatus)
  }

  // @@protoc_insertion_point(class_scope:ro.tuc.chat.proto_gen.MessageReadingStatus)
  private static final ro.tuc.chat.proto_gen.MessageReadingStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ro.tuc.chat.proto_gen.MessageReadingStatus();
  }

  public static ro.tuc.chat.proto_gen.MessageReadingStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageReadingStatus>
      PARSER = new com.google.protobuf.AbstractParser<MessageReadingStatus>() {
    @java.lang.Override
    public MessageReadingStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessageReadingStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageReadingStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ro.tuc.chat.proto_gen.MessageReadingStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

