// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

public interface MessageReadingStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.chat.proto_gen.MessageReadingStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string readerUserName = 1;</code>
   * @return The readerUserName.
   */
  java.lang.String getReaderUserName();
  /**
   * <code>string readerUserName = 1;</code>
   * @return The bytes for readerUserName.
   */
  com.google.protobuf.ByteString
      getReaderUserNameBytes();

  /**
   * <code>string senderUserName = 2;</code>
   * @return The senderUserName.
   */
  java.lang.String getSenderUserName();
  /**
   * <code>string senderUserName = 2;</code>
   * @return The bytes for senderUserName.
   */
  com.google.protobuf.ByteString
      getSenderUserNameBytes();

  /**
   * <code>string readMessagesUntil = 3;</code>
   * @return The readMessagesUntil.
   */
  java.lang.String getReadMessagesUntil();
  /**
   * <code>string readMessagesUntil = 3;</code>
   * @return The bytes for readMessagesUntil.
   */
  com.google.protobuf.ByteString
      getReadMessagesUntilBytes();
}
