// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

public interface OpenSessionRequestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.chat.proto_gen.OpenSessionRequestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromUserName = 1;</code>
   * @return The fromUserName.
   */
  java.lang.String getFromUserName();
  /**
   * <code>string fromUserName = 1;</code>
   * @return The bytes for fromUserName.
   */
  com.google.protobuf.ByteString
      getFromUserNameBytes();

  /**
   * <code>bool accepted = 2;</code>
   * @return The accepted.
   */
  boolean getAccepted();
}
