// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

public interface SendMessageStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.chat.proto_gen.SendMessageStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
   * @return The status.
   */
  ro.tuc.chat.proto_gen.Status getStatus();
  /**
   * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
   */
  ro.tuc.chat.proto_gen.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
   * @return Whether the sentMessage field is set.
   */
  boolean hasSentMessage();
  /**
   * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
   * @return The sentMessage.
   */
  ro.tuc.chat.proto_gen.ChatMessage getSentMessage();
  /**
   * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
   */
  ro.tuc.chat.proto_gen.ChatMessageOrBuilder getSentMessageOrBuilder();

  public ro.tuc.chat.proto_gen.SendMessageStatus.ResultCase getResultCase();
}
