// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

/**
 * Protobuf type {@code ro.tuc.chat.proto_gen.SendMessageStatus}
 */
public final class SendMessageStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ro.tuc.chat.proto_gen.SendMessageStatus)
    SendMessageStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SendMessageStatus.newBuilder() to construct.
  private SendMessageStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendMessageStatus() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SendMessageStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_SendMessageStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_SendMessageStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ro.tuc.chat.proto_gen.SendMessageStatus.class, ro.tuc.chat.proto_gen.SendMessageStatus.Builder.class);
  }

  private int resultCase_ = 0;
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    STATUS(1),
    SENTMESSAGE(2),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 1: return STATUS;
        case 2: return SENTMESSAGE;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  /**
   * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return resultCase_ == 1;
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.Status getStatus() {
    if (resultCase_ == 1) {
       return (ro.tuc.chat.proto_gen.Status) result_;
    }
    return ro.tuc.chat.proto_gen.Status.getDefaultInstance();
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.StatusOrBuilder getStatusOrBuilder() {
    if (resultCase_ == 1) {
       return (ro.tuc.chat.proto_gen.Status) result_;
    }
    return ro.tuc.chat.proto_gen.Status.getDefaultInstance();
  }

  public static final int SENTMESSAGE_FIELD_NUMBER = 2;
  /**
   * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
   * @return Whether the sentMessage field is set.
   */
  @java.lang.Override
  public boolean hasSentMessage() {
    return resultCase_ == 2;
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
   * @return The sentMessage.
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.ChatMessage getSentMessage() {
    if (resultCase_ == 2) {
       return (ro.tuc.chat.proto_gen.ChatMessage) result_;
    }
    return ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
  }
  /**
   * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
   */
  @java.lang.Override
  public ro.tuc.chat.proto_gen.ChatMessageOrBuilder getSentMessageOrBuilder() {
    if (resultCase_ == 2) {
       return (ro.tuc.chat.proto_gen.ChatMessage) result_;
    }
    return ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resultCase_ == 1) {
      output.writeMessage(1, (ro.tuc.chat.proto_gen.Status) result_);
    }
    if (resultCase_ == 2) {
      output.writeMessage(2, (ro.tuc.chat.proto_gen.ChatMessage) result_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resultCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ro.tuc.chat.proto_gen.Status) result_);
    }
    if (resultCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ro.tuc.chat.proto_gen.ChatMessage) result_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ro.tuc.chat.proto_gen.SendMessageStatus)) {
      return super.equals(obj);
    }
    ro.tuc.chat.proto_gen.SendMessageStatus other = (ro.tuc.chat.proto_gen.SendMessageStatus) obj;

    if (!getResultCase().equals(other.getResultCase())) return false;
    switch (resultCase_) {
      case 1:
        if (!getStatus()
            .equals(other.getStatus())) return false;
        break;
      case 2:
        if (!getSentMessage()
            .equals(other.getSentMessage())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (resultCase_) {
      case 1:
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SENTMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getSentMessage().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ro.tuc.chat.proto_gen.SendMessageStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ro.tuc.chat.proto_gen.SendMessageStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ro.tuc.chat.proto_gen.SendMessageStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ro.tuc.chat.proto_gen.SendMessageStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ro.tuc.chat.proto_gen.SendMessageStatus)
      ro.tuc.chat.proto_gen.SendMessageStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_SendMessageStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_SendMessageStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ro.tuc.chat.proto_gen.SendMessageStatus.class, ro.tuc.chat.proto_gen.SendMessageStatus.Builder.class);
    }

    // Construct using ro.tuc.chat.proto_gen.SendMessageStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusBuilder_ != null) {
        statusBuilder_.clear();
      }
      if (sentMessageBuilder_ != null) {
        sentMessageBuilder_.clear();
      }
      resultCase_ = 0;
      result_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ro.tuc.chat.proto_gen.Chat.internal_static_ro_tuc_chat_proto_gen_SendMessageStatus_descriptor;
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.SendMessageStatus getDefaultInstanceForType() {
      return ro.tuc.chat.proto_gen.SendMessageStatus.getDefaultInstance();
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.SendMessageStatus build() {
      ro.tuc.chat.proto_gen.SendMessageStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ro.tuc.chat.proto_gen.SendMessageStatus buildPartial() {
      ro.tuc.chat.proto_gen.SendMessageStatus result = new ro.tuc.chat.proto_gen.SendMessageStatus(this);
      if (resultCase_ == 1) {
        if (statusBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = statusBuilder_.build();
        }
      }
      if (resultCase_ == 2) {
        if (sentMessageBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = sentMessageBuilder_.build();
        }
      }
      result.resultCase_ = resultCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ro.tuc.chat.proto_gen.SendMessageStatus) {
        return mergeFrom((ro.tuc.chat.proto_gen.SendMessageStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ro.tuc.chat.proto_gen.SendMessageStatus other) {
      if (other == ro.tuc.chat.proto_gen.SendMessageStatus.getDefaultInstance()) return this;
      switch (other.getResultCase()) {
        case STATUS: {
          mergeStatus(other.getStatus());
          break;
        }
        case SENTMESSAGE: {
          mergeSentMessage(other.getSentMessage());
          break;
        }
        case RESULT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getSentMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int resultCase_ = 0;
    private java.lang.Object result_;
    public ResultCase
        getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public Builder clearResult() {
      resultCase_ = 0;
      result_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.Status, ro.tuc.chat.proto_gen.Status.Builder, ro.tuc.chat.proto_gen.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return resultCase_ == 1;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.Status getStatus() {
      if (statusBuilder_ == null) {
        if (resultCase_ == 1) {
          return (ro.tuc.chat.proto_gen.Status) result_;
        }
        return ro.tuc.chat.proto_gen.Status.getDefaultInstance();
      } else {
        if (resultCase_ == 1) {
          return statusBuilder_.getMessage();
        }
        return ro.tuc.chat.proto_gen.Status.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
     */
    public Builder setStatus(ro.tuc.chat.proto_gen.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
     */
    public Builder setStatus(
        ro.tuc.chat.proto_gen.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
     */
    public Builder mergeStatus(ro.tuc.chat.proto_gen.Status value) {
      if (statusBuilder_ == null) {
        if (resultCase_ == 1 &&
            result_ != ro.tuc.chat.proto_gen.Status.getDefaultInstance()) {
          result_ = ro.tuc.chat.proto_gen.Status.newBuilder((ro.tuc.chat.proto_gen.Status) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 1) {
          statusBuilder_.mergeFrom(value);
        } else {
          statusBuilder_.setMessage(value);
        }
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        if (resultCase_ == 1) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 1) {
          resultCase_ = 0;
          result_ = null;
        }
        statusBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
     */
    public ro.tuc.chat.proto_gen.Status.Builder getStatusBuilder() {
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.StatusOrBuilder getStatusOrBuilder() {
      if ((resultCase_ == 1) && (statusBuilder_ != null)) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 1) {
          return (ro.tuc.chat.proto_gen.Status) result_;
        }
        return ro.tuc.chat.proto_gen.Status.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.Status status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.Status, ro.tuc.chat.proto_gen.Status.Builder, ro.tuc.chat.proto_gen.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        if (!(resultCase_ == 1)) {
          result_ = ro.tuc.chat.proto_gen.Status.getDefaultInstance();
        }
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ro.tuc.chat.proto_gen.Status, ro.tuc.chat.proto_gen.Status.Builder, ro.tuc.chat.proto_gen.StatusOrBuilder>(
                (ro.tuc.chat.proto_gen.Status) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 1;
      onChanged();;
      return statusBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.ChatMessage, ro.tuc.chat.proto_gen.ChatMessage.Builder, ro.tuc.chat.proto_gen.ChatMessageOrBuilder> sentMessageBuilder_;
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
     * @return Whether the sentMessage field is set.
     */
    @java.lang.Override
    public boolean hasSentMessage() {
      return resultCase_ == 2;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
     * @return The sentMessage.
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.ChatMessage getSentMessage() {
      if (sentMessageBuilder_ == null) {
        if (resultCase_ == 2) {
          return (ro.tuc.chat.proto_gen.ChatMessage) result_;
        }
        return ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
      } else {
        if (resultCase_ == 2) {
          return sentMessageBuilder_.getMessage();
        }
        return ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
     */
    public Builder setSentMessage(ro.tuc.chat.proto_gen.ChatMessage value) {
      if (sentMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        sentMessageBuilder_.setMessage(value);
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
     */
    public Builder setSentMessage(
        ro.tuc.chat.proto_gen.ChatMessage.Builder builderForValue) {
      if (sentMessageBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        sentMessageBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
     */
    public Builder mergeSentMessage(ro.tuc.chat.proto_gen.ChatMessage value) {
      if (sentMessageBuilder_ == null) {
        if (resultCase_ == 2 &&
            result_ != ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance()) {
          result_ = ro.tuc.chat.proto_gen.ChatMessage.newBuilder((ro.tuc.chat.proto_gen.ChatMessage) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 2) {
          sentMessageBuilder_.mergeFrom(value);
        } else {
          sentMessageBuilder_.setMessage(value);
        }
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
     */
    public Builder clearSentMessage() {
      if (sentMessageBuilder_ == null) {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
        }
        sentMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
     */
    public ro.tuc.chat.proto_gen.ChatMessage.Builder getSentMessageBuilder() {
      return getSentMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
     */
    @java.lang.Override
    public ro.tuc.chat.proto_gen.ChatMessageOrBuilder getSentMessageOrBuilder() {
      if ((resultCase_ == 2) && (sentMessageBuilder_ != null)) {
        return sentMessageBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 2) {
          return (ro.tuc.chat.proto_gen.ChatMessage) result_;
        }
        return ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.ro.tuc.chat.proto_gen.ChatMessage sentMessage = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ro.tuc.chat.proto_gen.ChatMessage, ro.tuc.chat.proto_gen.ChatMessage.Builder, ro.tuc.chat.proto_gen.ChatMessageOrBuilder> 
        getSentMessageFieldBuilder() {
      if (sentMessageBuilder_ == null) {
        if (!(resultCase_ == 2)) {
          result_ = ro.tuc.chat.proto_gen.ChatMessage.getDefaultInstance();
        }
        sentMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ro.tuc.chat.proto_gen.ChatMessage, ro.tuc.chat.proto_gen.ChatMessage.Builder, ro.tuc.chat.proto_gen.ChatMessageOrBuilder>(
                (ro.tuc.chat.proto_gen.ChatMessage) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 2;
      onChanged();;
      return sentMessageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ro.tuc.chat.proto_gen.SendMessageStatus)
  }

  // @@protoc_insertion_point(class_scope:ro.tuc.chat.proto_gen.SendMessageStatus)
  private static final ro.tuc.chat.proto_gen.SendMessageStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ro.tuc.chat.proto_gen.SendMessageStatus();
  }

  public static ro.tuc.chat.proto_gen.SendMessageStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendMessageStatus>
      PARSER = new com.google.protobuf.AbstractParser<SendMessageStatus>() {
    @java.lang.Override
    public SendMessageStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SendMessageStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendMessageStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ro.tuc.chat.proto_gen.SendMessageStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

