// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

public interface SessionClosedUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.chat.proto_gen.SessionClosedUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string partnerName = 1;</code>
   * @return The partnerName.
   */
  java.lang.String getPartnerName();
  /**
   * <code>string partnerName = 1;</code>
   * @return The bytes for partnerName.
   */
  com.google.protobuf.ByteString
      getPartnerNameBytes();
}
