// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ro.tuc.chat.proto_gen;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ro.tuc.chat.proto_gen.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestSenderName = 1;</code>
   * @return The requestSenderName.
   */
  java.lang.String getRequestSenderName();
  /**
   * <code>string requestSenderName = 1;</code>
   * @return The bytes for requestSenderName.
   */
  com.google.protobuf.ByteString
      getRequestSenderNameBytes();

  /**
   * <code>string partnerName = 2;</code>
   * @return The partnerName.
   */
  java.lang.String getPartnerName();
  /**
   * <code>string partnerName = 2;</code>
   * @return The bytes for partnerName.
   */
  com.google.protobuf.ByteString
      getPartnerNameBytes();
}
